insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (33, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (40, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (34, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (15, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (45, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (11, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (45, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (40, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (33, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (45, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (40, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (11, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (11, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (11, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (68, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (45, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (68, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (21, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (15, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'Jerico N', 239);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (68, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (7, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (40, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (45, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (11, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (68, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (28, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (28, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (33, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (21, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (40, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (7, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (15, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (34, 'GV Mavid', 80);
insert into drino_sales (user_id, product, price) values (33, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (34, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (68, 'Legacy Pro7', 156);
insert into drino_sales (user_id, product, price) values (2, 'Sensation L3', 374);
insert into drino_sales (user_id, product, price) values (11, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (11, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (45, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (2, 'VIN Mono 6', 249);
insert into drino_sales (user_id, product, price) values (15, 'ModelX', 499);
insert into drino_sales (user_id, product, price) values (4, 'VIN Mono 6', 249);
